### ISSUE TITLE
feat : watch 뷰 그리기

### ISSUE THREAD

**Issue by cutthebutter** [cutthebutter/ModeraIOSWatch#2]
## 📌 Issue
워치의 뷰를 그립니다. 
<img width="679" alt="image" src="https://github.com/cutthebutter/ModeraIOSWatch/assets/42573282/dce424f6-6808-4a4e-8dc2-5097136aa580">

## 📝 To-do
- [ ]  앱 들어가자마자 음성인식 뜨기
- [ ] 탭 뷰 만들기
- [ ] 메인뷰의 뷰 만들기 
- [ ] 메모 리스트 뷰 만들기
- [ ] 메모 리스트의 디테일 뷰 만들기

**Comment by cutthebutter** [comment]
git fetch origin
git checkout 2-feat-watch-뷰-그리기
